name: GBPyro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - arviz
  - theano
  - mkl-service
  - jupyterlab
  - seaborn
  - pandas
  - astropy
  - nodejs
  - ipywidgets
  - tqdm
  - pymc3
