name: GBPyro
channels:
  - conda-forge
  - defaults
dependencies:
  - mkl-service
  - tqdm
  - theano
  - python=3.7
  - arviz
  - astropy
  - jupyterlab
  - nodejs
  - pandas
  - ipywidgets
  - seaborn
  - pymc3
  - corner
