name: GBPyro
channels:
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - python=3.7
  - arviz
  - pip
  - pip:
    - pyro-ppl
  - jupyterlab
  - seaborn
  - pandas
  - astropy
  - nodejs
  - ipywidgets
  - tqdm
